AntJob.Web/Areas/Ant/Controllers/AppOnlineController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using AntJob.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using NewLife.Cube;
using NewLife.Web;

namespace AntJob.Web.Areas.Ant.Controllers
{
    /// <summary>应用在线</summary>
    [AntArea]
    [DisplayName("应用在线")]
    public class AppOnlineController : EntityController<AppOnline>
    {
        static AppOnlineController()
        {
            MenuOrder = 90;

            AppOnline.Meta.Table.DataTable.InsertOnly = true;
        }

        /// <summary>搜索数据集</summary>
        /// <param name="p"></param>
        /// <returns></returns>
        protected override IEnumerable<AppOnline> Search(Pager p)
        {
            var appid = p["appid"].ToInt(-1);
            var start = p["dtStart"].ToDateTime();
            var end = p["dtEnd"].ToDateTime();

            return AppOnline.Search(appid, start, end, p["q"], p);
        }
    }
}

AntJob.Web/Areas/Ant/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Threading.Tasks;
using AntJob.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using NewLife;
using NewLife.Cube;
using NewLife.Security;
using NewLife.Web;
using XCode;
using XCode.Membership;

namespace AntJob.Web.Areas.Ant.Controllers
{
    /// <summary>作业</summary>
    [AntArea]
    [DisplayName("作业")]
    public class JobController : EntityController<Job>
    {
        static JobController()
        {
            var list = ListFields;
            list.RemoveField("Type");
            list.RemoveField("CreateUserID");
            list.RemoveField("CreateTime");
            list.RemoveField("CreateIP");
            list.RemoveField("UpdateUserID");
            list.RemoveField("UpdateIP");

            MenuOrder = 80;
        }

        public JobController() => PageSetting.EnableAdd = false;

        /// <summary>搜索数据集</summary>
        /// <param name="p"></param>
        /// <returns></returns>
        protected override IEnumerable<Job> Search(Pager p)
        {
            var id = p["ID"].ToInt(-1);
            var appid = p["appid"].ToInt(-1);
            var start = p["dtStart"].ToDateTime();
            var end = p["dtEnd"].ToDateTime();
            var mode = p["Mode"].ToInt(-1);

            return Job.Search(id, appid, start, end, mode, p["q"], p);
        }

        /// <summary>启用禁用任务</summary>
        /// <param name="id"></param>
        /// <param name="enable"></param>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult Set(Int32 id = 0, Boolean enable = true)
        {
            if (id > 0)
            {
                var dt = Job.FindByID(id);
                if (dt == null) throw new ArgumentNullException(nameof(id), "找不到任务 " + id);

                dt.Enable = enable;
                dt.Save();
            }
            else
            {
                var ids = GetRequest("keys").SplitAsInt();

                foreach (var item in ids)
                {
                    var dt = Job.FindByID(item);
                    if (dt != null && dt.Enable != enable)
                    {
                        dt.Enable = enable;
                        dt.Save();
                    }
                }
            }
            return JsonRefresh("操作成功！");
        }

        /// <summary>
        /// 重置时间
        /// </summary>
        /// <param name="days"></param>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult ResetTime(Int32 days = 0)
        {
            var ids = GetRequest("keys").SplitAsInt();
            var st = GetRequest("sday").ToDateTime();
            var et = GetRequest("eday").ToDateTime();
            Parallel.ForEach(ids, k =>
            {
                var dt = Job.FindByID(k);
                dt?.ResetTime(days, st, et);
            });

            return JsonRefresh("操作成功！");
        }

        /// <summary>完全重置</summary>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult ResetOther()
        {
            var ids = GetRequest("keys").SplitAsInt();
            Parallel.ForEach(ids, k =>
            {
                var dt = Job.FindByID(k);
                dt?.ResetOther();
            });

            return JsonRefresh("操作成功！");
        }

        /// <summary>设置偏移</summary>
        /// <param name="offset">偏移</param>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult SetOffset(Int32 offset)
        {
            if (offset < 0) offset = 15;

            var ids = GetRequest("keys").SplitAsInt();
            Parallel.ForEach(ids, k =>
            {
                var dt = Job.FindByID(k);
                if (dt != null)
                {
                    dt.Offset = offset;
                    dt.Save();
                }
            });

            return JsonRefresh("操作成功！");
        }

        /// <summary>清空错误数</summary>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult ClearError()
        {
            var ids = GetRequest("keys").SplitAsInt();
            Parallel.ForEach(ids, k =>
            {
                var dt = Job.FindByID(k);
                if (dt != null)
                {
                    dt.Error = 0;
                    dt.Save();
                }
            });

            return JsonRefresh("操作成功！");
        }

        /// <summary>克隆一个作业</summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult Clone(Int32 id)
        {
            var job = Job.FindByID(id);
            if (job == null) return Index();

            // 拷贝一次对象，避免因为缓存等原因修改原来的数据
            job = job.Clone() as Job;

            // 随机名称，插入新行
            job.ID = 0;
            job.Name = Rand.NextString(8);
            job.Enable = false;
            job.Insert();

            // 跳转到编辑页，这里时候已经得到新的自增ID
            return Edit(job.ID + "");
        }

        protected override Boolean Valid(Job entity, DataObjectMethodType type, Boolean post)
        {
            if (!post) return base.Valid(entity, type, post);

            var act = type switch
            {
                DataObjectMethodType.Update => "修改",
                DataObjectMethodType.Insert => "添加",
                DataObjectMethodType.Delete => "删除",
                _ => type + "",
            };

            // 必须提前写修改日志，否则修改后脏数据失效，保存的日志为空
            if (type == DataObjectMethodType.Update && (entity as IEntity).HasDirty)
                LogProvider.Provider.WriteLog(act, entity);

            var err = "";
            try
            {
                return base.Valid(entity, type, post);
            }
            catch (Exception ex)
            {
                err = ex.Message;
                throw;
            }
            finally
            {
                LogProvider.Provider.WriteLog(act, entity, err);
            }
        }
    }
}

AntJob.Web/Areas/Ant/Controllers/JobErrorController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using AntJob.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using NewLife.Cube;
using NewLife.Web;

namespace AntJob.Web.Areas.Ant.Controllers
{
    /// <summary>作业错误</summary>
    [AntArea]
    [DisplayName("作业错误")]
    public class JobErrorController : EntityController<JobError>
    {
        static JobErrorController() => MenuOrder = 60;

        /// <summary>搜索数据集</summary>
        /// <param name="p"></param>
        /// <returns></returns>
        protected override IEnumerable<JobError> Search(Pager p)
        {
            var appid = p["appid"].ToInt(-1);
            var jobid = p["JobID"].ToInt(-1);
            var start = p["dtStart"].ToDateTime();
            var end = p["dtEnd"].ToDateTime();
            var client = p["Client"];

            return JobError.Search(appid, jobid, client, start, end, p["q"], p);
        }
    }
}

AntJob.Web/Areas/Ant/Controllers/JobTaskController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using AntJob.Data;
using AntJob.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using NewLife;
using NewLife.Cube;
using NewLife.Web;
using XCode.Membership;

namespace AntJob.Web.Areas.Ant.Controllers
{
    /// <summary>作业任务</summary>
    [AntArea]
    [DisplayName("作业任务")]
    public class JobTaskController : EntityController<JobTask>
    {
        static JobTaskController()
        {
            MenuOrder = 70;

            JobTask.Meta.Modules.Add<TimeModule>();
        }

        /// <summary>搜索数据集</summary>
        /// <param name="p"></param>
        /// <returns></returns>
        protected override IEnumerable<JobTask> Search(Pager p)
        {
            var id = p["id"].ToInt(-1);
            var jobid = p["JobID"].ToInt(-1);
            var appid = p["AppID"].ToInt(-1);
            var status = (JobStatus)p["Status"].ToInt(-1);
            var start = p["dtStart"].ToDateTime();
            var end = p["dtEnd"].ToDateTime();
            var client = p["Client"];

            return JobTask.Search(id, appid, jobid, status, start, end, client, p["q"], p);
        }

        /// <summary>修改状态</summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [EntityAuthorize(PermissionFlags.Update)]
        public ActionResult Set(Int32 id = 0)
        {
            if (id > 0)
            {
                var dt = JobTask.FindByID(id);
                if (dt == null) throw new ArgumentNullException(nameof(id), "找不到任务 " + id);

                dt.Status = JobStatus.取消;
                if (dt.Times >= 10) dt.Times = 0;

                dt.Save();
            }
            else
            {
                var ids = GetRequest("keys").SplitAsInt();

                foreach (var item in ids)
                {
                    var dt = JobTask.FindByID(item);
                    if (dt != null)
                    {
                        dt.Status = JobStatus.取消;
                        if (dt.Times >= 10) dt.Times = 0;

                        dt.Save();
                    }
                }
            }
            return JsonRefresh("操作成功！");
        }
    }
}

AntJob.Web/Areas/Ant/Views/App/_List_Data.cshtml
@model IList<AntJob.Data.Entity.App>
@using NewLife;
@using NewLife.Web;
@using XCode;
@using XCode.Configuration;
@{
    var fact = ViewBag.Factory as IEntityFactory;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;
    var provider = ManageProvider.Provider;
}
<table class="table table-bordered table-hover table-striped table-condensed">
    <thead>
        <tr>
            @if (set.EnableSelect)
            {
                <th class="text-center" style="width:10px;"><input type="checkbox" id="chkAll" title="全选" /></th>
            }
            <th class="text-center hidden-md hidden-sm hidden-xs"><a href="@Html.Raw(page.GetSortUrl("ID"))">编号</a></th>
            <th class="text-center"><a href="@Html.Raw(page.GetSortUrl("Name"))">名称</a></th>
            <th class="text-center"><a href="@Html.Raw(page.GetSortUrl("DisplayName"))">显示名</a></th>
            <th class="text-center"><a href="@Html.Raw(page.GetSortUrl("MessageCount"))">消息数</a></th>
            <th class="text-center"><a href="@Html.Raw(page.GetSortUrl("JobCount"))">作业数</a></th>
            <th class="text-center"><a href="@Html.Raw(page.GetSortUrl("Enable"))">启用</a></th>
            <th class="text-center">消息</th>
            <th class="text-center">在线</th>
            <th class="text-center">任务</th>
            <th class="text-center">错误</th>
            <th class="text-center">配置</th>
            <th class="text-center">历史</th>
            <th class="text-center" style="min-width:134px;"><a href="@Html.Raw(page.GetSortUrl("UpdateTime"))">更新时间</a></th>
            @if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {
                <th class="text-center" style="min-width:100px;">操作</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var entity in Model)
        {
            <tr>
                @if (set.EnableSelect)
                {
                    <td class="text-center"><input type="checkbox" name="keys" value="@entity.ID" /></td>
                }
                <td class="text-center hidden-md hidden-sm hidden-xs">@entity.ID</td>
                <td class="text-center"><a href="@Url.Action("Index","Job",new {appid=entity.ID})">@entity.Name</a></td>
                <td>@entity.DisplayName</td>
                <td>@entity.MessageCount.ToString("n0")</td>
                <td class="text-center"><a href="@Url.Action("Index","Job",new {appid=entity.ID})">@entity.JobCount</a></td>
                <td class="text-center">
                    <a href="App/Set/@entity.ID?enable=@(entity.Enable?"false":"true")" data-action="action"><i class="glyphicon glyphicon-@(entity.Enable ? "ok" : "remove")" style="color: @(entity.Enable ? "green" : "red");"></i></a>
                </td>
                <td class="text-center"><a href="@Url.Action("Index","AppMessage",new {appid=entity.ID})">消息</a></td>
                <td class="text-center"><a href="@Url.Action("Index","AppOnline",new {appid=entity.ID})">在线</a></td>
                <td class="text-center"><a href="@Url.Action("Index","JobTask",new {appid=entity.ID})">任务</a></td>
                <td class="text-center"><a href="@Url.Action("Index","JobError",new {appid=entity.ID})">错误</a></td>
                <td class="text-center"><a href="AppConfig?appId=@entity.ID">配置</a></td>
                <td class="text-center"><a href="AppHistory?appId=@entity.ID">历史</a></td>
                <td>@entity.UpdateTime.ToFullString("")</td>
                @if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {
                    <td class="text-center">
                        @await Html.PartialAsync("_List_Data_Action", (Object)entity)
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

AntJob.Web/Areas/Ant/Views/App/_List_Search.cshtml
@using AntJob.Data.Entity;
@{
    var page = ViewBag.Page as Pager;
    var dic = new Dictionary<Int32, String>();
    dic.Add(1, "启用");
    dic.Add(0, "禁用");
}
<div class="form-group">
    <label for="enable" class="control-label">状态：</label>
    @Html.ForDropDownList("enable", dic, page["enable"], "全部", true)
    <label for="category" class="control-label">分类：</label>
    @Html.ForDropDownList("category", AntJob.Data.Entity.App.FindAllCategoryByCache(), page["category"], "全部", true)
</div>

AntJob.Web/Areas/Ant/Views/App/_List_Toolbar_Batch.cshtml
@using NewLife.Common;
@using System.Collections.Generic;
@{
    var user = ViewBag.User as IUser ?? User.Identity as IUser;
    var fact = ViewBag.Factory as IEntityFactory;
    var set = ViewBag.PageSetting as PageSetting;

}
@if (set.EnableSelect)
{
    <button type="button" class="btn btn-warning btn-sm" data-action="action" data-url="@Url.Action("ResetApp")" data-fields="keys" disabled>
        <span title="清空作业、作业项、统计、错误，开始时间设为本月一号">重置</span>
    </button>
    <button type="button" class="btn btn-success btn-sm" data-action="action" data-url="@Url.Action("Set")?enable=true" data-fields="keys" disabled>
        批量启用
    </button>
    <button type="button" class="btn btn-error btn-sm" data-action="action" data-url="@Url.Action("Set")?enable=false" data-fields="keys" disabled>
        批量禁用
    </button>
}